<?php
/**
 * Tv_ActionAdmin.php
 * 
 * @author Technovarth
 * @package SNSV
 */

/**
 * 管理アクションクラスリスト
 * /bin/make_action_array.phpを起動して生成したアクションリストの配列を管理する
 *
 * @author Technovarth
 * @access public
 * @package SNSV
 */
class Tv_ActionListManager extends Ethna_AppManager
{
	/**
	 * アクション名（英語、日本語）を返却する
	 * 
	 * @access public
	 * @return array
	 */
	function getActionList()
	{
		$action_array = array(
			'Tv_Action_UserAdList' => 'ユーザ広告一覧' ,
			'Tv_Action_UserAdRedirect' => 'ユーザ広告リダイレクト' ,
			'Tv_Action_UserAd' => 'ユーザ広告ポータル' ,
			'Tv_Action_UserAvatarBuyDo' => 'ユーザアバター購入実行' ,
			'Tv_Action_UserAvatarBuy' => 'ユーザアバター購入' ,
			'Tv_Action_UserAvatarChangeDo' => 'ユーザアバター変更実行' ,
			'Tv_Action_UserAvatarConfigConfirm' => 'ユーザアバター設定確認' ,
			'Tv_Action_UserAvatarConfigDo' => 'ユーザアバター設定実行' ,
			'Tv_Action_UserAvatarConfigFirst' => 'ユーザアバター設定ページ1' ,
			'Tv_Action_UserAvatarConfigSecond' => 'ユーザアバター設定ページ2' ,
			'Tv_Action_UserAvatarHome' => 'ユーザアバターホーム' ,
			'Tv_Action_UserAvatarList' => 'ユーザアバター一覧' ,
			'Tv_Action_UserAvatarPreview' => 'ユーザアバタープレビュー' ,
			'Tv_Action_UserAvatarRanking' => 'ユーザアバターランキング' ,
			'Tv_Action_UserAvatar' => 'ユーザアバターポータル' ,
			'Tv_Action_UserBannerRedirect' => 'ユーザバナーリダイレクト' ,
			'Tv_Action_UserBbsAddConfirm' => 'ユーザ伝言登録確認' ,
			'Tv_Action_UserBbsAddDo' => 'ユーザ伝言登録実行' ,
			'Tv_Action_UserBbsAdd' => 'ユーザ伝言登録' ,
			'Tv_Action_UserBbsDeleteConfirm' => 'ユーザ伝言削除確認' ,
			'Tv_Action_UserBbsDeleteDo' => 'ユーザ伝言削除実行' ,
			'Tv_Action_UserBbsEditConfirm' => 'ユーザ伝言編集確認' ,
			'Tv_Action_UserBbsEditDo' => 'ユーザ伝言編集実行' ,
			'Tv_Action_UserBbsEdit' => 'ユーザ伝言編集' ,
			'Tv_Action_UserBbsList' => 'ユーザ伝言メッセージ一覧' ,
			'Tv_Action_UserBlacklistAddConfirm' => 'ユーザブラックリスト登録確認' ,
			'Tv_Action_UserBlacklistAddDo' => 'ユーザブラックリスト登録実行' ,
			'Tv_Action_UserBlacklistDeleteConfirm' => 'ユーザブラックリスト削除確認' ,
			'Tv_Action_UserBlacklistDeleteDo' => 'ユーザブラックリスト削除実行' ,
			'Tv_Action_UserBlacklistList' => 'ユーザブラックリスト一覧' ,
			'Tv_Action_UserBlogArticleAddConfirm' => 'ユーザ日記登録確認' ,
			'Tv_Action_UserBlogArticleAddDo' => 'ユーザ日記登録' ,
			'Tv_Action_UserBlogArticleAdd' => 'ユーザ日記登録' ,
			'Tv_Action_UserBlogArticleDeleteConfirm' => 'ユーザ日記削除確認' ,
			'Tv_Action_UserBlogArticleDeleteDo' => 'ユーザ日記削除実行' ,
			'Tv_Action_UserBlogArticleEditConfirm' => 'ユーザ日記編集確認' ,
			'Tv_Action_UserBlogArticleEditDo' => 'ユーザ日記編集実行' ,
			'Tv_Action_UserBlogArticleEdit' => 'ユーザ日記編集' ,
			'Tv_Action_UserBlogArticleList' => 'ユーザ日記一覧' ,
			'Tv_Action_UserBlogArticleSearch' => 'ユーザ日記検索' ,
			'Tv_Action_UserBlogArticleView' => 'ユーザ日記閲覧' ,
			'Tv_Action_UserBlogCommentAddConfirm' => 'ユーザ日記コメント登録確認' ,
			'Tv_Action_UserBlogCommentAddDo' => 'ユーザ日記コメント登録実行' ,
			'Tv_Action_UserBlogCommentAdd' => 'ユーザ日記コメント追加' ,
			'Tv_Action_UserBlogCommentDeleteConfirm' => 'ユーザ日記コメント削除確認' ,
			'Tv_Action_UserBlogCommentDeleteDo' => 'ユーザ日記コメント削除実行' ,
			'Tv_Action_UserBlogCommentEditConfirm' => 'ユーザ日記コメント編集確認' ,
			'Tv_Action_UserBlogCommentEditDo' => 'ユーザ日記コメント編集実行' ,
			'Tv_Action_UserBlogCommentEdit' => 'ユーザ日記コメント編集' ,
			'Tv_Action_UserBlogCommentView' => 'ユーザ日記コメント閲覧' ,
			'Tv_Action_UserBlogRecent' => 'ユーザ最新記事' ,
			'Tv_Action_UserBlogView' => 'ユーザ記事閲覧' ,
			'Tv_Action_UserCap' => 'ユーザ画像認証' ,
			'Tv_Action_UserCommentAddConfirm' => 'ユーザコメント登録確認' ,
			'Tv_Action_UserCommentAddDo' => 'ユーザコメント登録実行' ,
			'Tv_Action_UserCommentDeleteConfirm' => 'ユーザコメント削除確認' ,
			'Tv_Action_UserCommentDeleteDo' => 'ユーザコメント削除実行' ,
			'Tv_Action_UserCommentEditConfirm' => 'ユーザコメント編集確認' ,
			'Tv_Action_UserCommentEditDo' => 'ユーザコメント編集実行' ,
			'Tv_Action_UserCommentEdit' => 'ユーザコメント編集' ,
			'Tv_Action_UserCommentList' => 'ユーザコメント一覧' ,
			'Tv_Action_UserCommunityAcceptDo' => 'ユーザコミュニティ承認実行' ,
			'Tv_Action_UserCommunityAccept' => 'ユーザコミュニティ承認' ,
			'Tv_Action_UserCommunityAddConfirm' => 'ユーザコミュニティ登録確認' ,
			'Tv_Action_UserCommunityAddDo' => 'ユーザコミュニティ登録実行' ,
			'Tv_Action_UserCommunityAdd' => 'ユーザコミュニティ登録' ,
			'Tv_Action_UserCommunityAdminMemberRemoveConfirm' => 'ユーザコミュニティ管理者メンバー削除確認' ,
			'Tv_Action_UserCommunityAdminMemberRemoveDo' => 'ユーザコミュニティ管理者メンバー削除実行' ,
			'Tv_Action_UserCommunityAdminMember' => 'ユーザコミュニティ管理者メンバー' ,
			'Tv_Action_UserCommunityAdminPowerGiveConfirm' => 'ユーザコミュニティ管理者権限譲渡確認' ,
			'Tv_Action_UserCommunityAdminPowerGiveDo' => 'ユーザコミュニティ管理者権限譲渡実行' ,
			'Tv_Action_UserCommunityArticleAddConfirm' => 'ユーザコミュニティトピック登録確認' ,
			'Tv_Action_UserCommunityArticleAddDo' => 'ユーザコミュニティトピック登録実行' ,
			'Tv_Action_UserCommunityArticleAdd' => 'ユーザコミュニティトピック登録' ,
			'Tv_Action_UserCommunityArticleDeleteConfirm' => 'ユーザコミュニティトピック削除確認' ,
			'Tv_Action_UserCommunityArticleDeleteDo' => 'ユーザコミュニティトピック削除実行' ,
			'Tv_Action_UserCommunityArticleEditConfirm' => 'ユーザコミュニティトピック編集確認' ,
			'Tv_Action_UserCommunityArticleEditDo' => 'ユーザコミュニティトピック編集実行' ,
			'Tv_Action_UserCommunityArticleEdit' => 'ユーザコミュニティトピック編集' ,
			'Tv_Action_UserCommunityArticleList' => 'ユーザコミュニティ記事一覧' ,
			'Tv_Action_UserCommunityArticleSearch' => 'ユーザコミュニティトピック検索' ,
			'Tv_Action_UserCommunityArticleView' => 'ユーザコミュニティトピック閲覧' ,
			'Tv_Action_UserCommunityBaseAdminOnly' => 'コミュニティ管理人のみがアクセスできる' ,
			'Tv_Action_UserCommunityBaseUserOnly' => 'コミュニティメンバのみがアクセスできる' ,
			'Tv_Action_UserCommunityCommentAddConfirm' => 'ユーザコミュニティコメント登録確認' ,
			'Tv_Action_UserCommunityCommentAddDo' => 'ユーザコミュニティコメント登録実行' ,
			'Tv_Action_UserCommunityCommentDeleteConfirm' => 'ユーザコミュニティコメント削除確認' ,
			'Tv_Action_UserCommunityCommentDeleteDo' => 'ユーザコミュニティコメント削除実行' ,
			'Tv_Action_UserCommunityCommentEditConfirm' => 'ユーザコミュニティコメント編集確認' ,
			'Tv_Action_UserCommunityCommentEditDo' => 'ユーザコミュニティコメント編集実行' ,
			'Tv_Action_UserCommunityCommentEdit' => 'ユーザコミュニティコメント編集' ,
			'Tv_Action_UserCommunityDeleteConfirm' => 'ユーザコミュニティ削除確認' ,
			'Tv_Action_UserCommunityDeleteDo' => 'ユーザコミュニティ削除実行' ,
			'Tv_Action_UserCommunityEditConfirm' => 'ユーザコミュニティ編集確認' ,
			'Tv_Action_UserCommunityEditDo' => 'ユーザコミュニティ編集実行' ,
			'Tv_Action_UserCommunityEdit' => 'ユーザコミュニティ編集' ,
			'Tv_Action_UserCommunityJoinDo' => 'ユーザコミュニティ参加実行' ,
			'Tv_Action_UserCommunityList' => 'ユーザコミュニティ一覧' ,
			'Tv_Action_UserCommunityMember' => 'ユーザコミュニティメンバー' ,
			'Tv_Action_UserCommunityRecent' => 'ユーザコミュニティ最新コメント' ,
			'Tv_Action_UserCommunityResignConfirm' => 'ユーザコミュニティ退会確認' ,
			'Tv_Action_UserCommunityResignDo' => 'ユーザコミュニティ退会実行' ,
			'Tv_Action_UserCommunitySearch' => 'ユーザコミュニティ検索' ,
			'Tv_Action_UserCommunityView' => 'ユーザコミュニティ閲覧' ,
			'Tv_Action_UserConfigLoginEditDo' => 'ユーザかんたんログイン設定変更実行' ,
			'Tv_Action_UserConfigLoginEdit' => 'ユーザ簡単ログイン設定変更' ,
			'Tv_Action_UserConfigMailEdit' => 'ユーザメールアドレス変更' ,
			'Tv_Action_UserConfigPassEditDo' => 'ユーザパスワード変更実行' ,
			'Tv_Action_UserConfigPassEdit' => 'ユーザパスワード変更' ,
			'Tv_Action_UserConfigReceiveEditDo' => 'ユーザ設定変更実行' ,
			'Tv_Action_UserConfigReceiveEdit' => 'ユーザメッセージ受信ステータス変更' ,
			'Tv_Action_UserConfig' => 'ユーザ設定' ,
			'Tv_Action_UserContents' => 'ユーザフリーページ' ,
			'Tv_Action_UserDecomailBuyDo' => 'ユーザデコメール購入実行' ,
			'Tv_Action_UserDecomailBuy' => 'ユーザデコメール購入' ,
			'Tv_Action_UserDecomailHome' => 'ユーザデコメールホーム' ,
			'Tv_Action_UserDecomailList' => 'ユーザデコメール一覧' ,
			'Tv_Action_UserDecomailRanking' => 'ユーザデコメールランキング' ,
			'Tv_Action_UserDecomail' => 'ユーザデコメールポータル' ,
			'Tv_Action_UserFileAvatarPreview' => 'ユーザアバタープレビュー' ,
			'Tv_Action_UserFileAvatarView' => 'ユーザアバター閲覧' ,
			'Tv_Action_UserFileGet' => 'ユーザファイル取得' ,
			'Tv_Action_UserFileImageView' => 'ユーザ画像表示' ,
			'Tv_Action_UserFootprint' => 'ユーザあしあと画面' ,
			'Tv_Action_UserFriendAcceptDo' => 'ユーザ友達リンク承認実行' ,
			'Tv_Action_UserFriendAccept' => 'ユーザ友達承認一覧' ,
			'Tv_Action_UserFriendApplyConfirm' => 'ユーザ友達申請確認' ,
			'Tv_Action_UserFriendApplyDo' => 'ユーザ友達申請実行' ,
			'Tv_Action_UserFriendApply' => 'ユーザ友達申請' ,
			'Tv_Action_UserFriendDeleteConfirm' => 'ユーザ友達削除確認' ,
			'Tv_Action_UserFriendDeleteDo' => 'ユーザ友達削除実行' ,
			'Tv_Action_UserFriendDelete' => 'ユーザ友達削除' ,
			'Tv_Action_UserFriendIntroductionDeleteConfirm' => 'ユーザ友達紹介文削除確認' ,
			'Tv_Action_UserFriendIntroductionDeleteDo' => 'ユーザ友達紹介文削除実行' ,
			'Tv_Action_UserFriendIntroductionEditConfirm' => 'ユーザ友達紹介文編集確認' ,
			'Tv_Action_UserFriendIntroductionEditDo' => 'ユーザ友達紹介文編集実行' ,
			'Tv_Action_UserFriendIntroductionEdit' => 'ユーザ友達紹介文編集' ,
			'Tv_Action_UserFriendIntroductionList' => 'ユーザ友達紹介文一覧' ,
			'Tv_Action_UserFriendList' => 'ユーザ友達一覧' ,
			'Tv_Action_UserGameBuyDo' => 'ユーザゲーム購入実行' ,
			'Tv_Action_UserGameBuy' => 'ユーザゲーム購入' ,
			'Tv_Action_UserGameFinish' => 'ユーザゲーム終了' ,
			'Tv_Action_UserGameHome' => 'ユーザゲームホーム' ,
			'Tv_Action_UserGameList' => 'ユーザゲーム一覧' ,
			'Tv_Action_UserGameRanking' => 'ユーザゲームアランキングクション' ,
			'Tv_Action_UserGameScoreAdd' => 'ユーザゲームスコア登録' ,
			'Tv_Action_UserGameScoreList' => 'ユーザゲームスコア一覧' ,
			'Tv_Action_UserGame' => 'ユーザゲームポータル' ,
			'Tv_Action_UserHome' => 'ユーザマイページ' ,
			'Tv_Action_UserIndex' => 'ユーザ非会員トップ' ,
			'Tv_Action_UserInviteConfirm' => 'ユーザ招待確認' ,
			'Tv_Action_UserInviteDo' => 'ユーザ招待実行' ,
			'Tv_Action_UserInvite' => 'ユーザ招待' ,
			'Tv_Action_UserLoginDo' => 'ユーザログイン実行' ,
			'Tv_Action_UserLogin' => 'ユーザログイン' ,
			'Tv_Action_UserLogoutDo' => 'ユーザログアウト実行' ,
			'Tv_Action_UserLogout' => 'ユーザログアウト' ,
			'Tv_Action_UserMessageDeleteReceivedConfirm' => 'ユーザ受信メッセージ削除確認' ,
			'Tv_Action_UserMessageDeleteReceivedDo' => 'ユーザ受信メッセージ削除実行' ,
			'Tv_Action_UserMessageDeleteSentConfirm' => 'ユーザ送信済みメッセージ削除確認' ,
			'Tv_Action_UserMessageDeleteSentDo' => 'ユーザ送信済みメッセージ削除実行' ,
			'Tv_Action_UserMessageListReceived' => 'ユーザ受信メッセージ一覧' ,
			'Tv_Action_UserMessageListSent' => 'ユーザ送信メッセージ一覧' ,
			'Tv_Action_UserMessageReply' => 'ユーザメッセージ返信' ,
			'Tv_Action_UserMessageSendConfirm' => 'ユーザメッセージ送信確認' ,
			'Tv_Action_UserMessageSendDo' => 'ユーザメッセージ送信実行' ,
			'Tv_Action_UserMessageSend' => 'ユーザメッセージ送信' ,
			'Tv_Action_UserMessageViewReceived' => 'ユーザ受信メッセージ閲覧' ,
			'Tv_Action_UserMessageViewSent' => 'ユーザ送信済みメッセージ閲覧' ,
			'Tv_Action_UserNewsList' => 'ユーザニュース一覧' ,
			'Tv_Action_UserNewsView' => 'ユーザニュース閲覧' ,
			'Tv_Action_UserPointHome' => 'ユーザポイント通帳ホーム' ,
			'Tv_Action_UserProfileEditDo' => 'ユーザプロフィール変更実行' ,
			'Tv_Action_UserProfileEdit' => 'ユーザプロフィール編集' ,
			'Tv_Action_UserProfileFriendList' => 'ユーザ対象者の友達一覧' ,
			'Tv_Action_UserProfileView' => 'ユーザプロフィール閲覧' ,
			'Tv_Action_UserRegistDo' => 'ユーザ登録実行' ,
			'Tv_Action_UserRegist' => 'ユーザ登録' ,
			'Tv_Action_UserRemindDo' => 'ユーザパスワード請求' ,
			'Tv_Action_UserRemind' => 'ユーザパスワードリマインダー' ,
			'Tv_Action_UserReportSendConfirm' => 'ユーザ通報送信確認' ,
			'Tv_Action_UserReportSendDo' => 'ユーザ通報送信実行' ,
			'Tv_Action_UserReportSend' => 'ユーザ通報送信' ,
			'Tv_Action_UserResignConfirm' => 'ユーザ退会確認' ,
			'Tv_Action_UserResignDo' => 'ユーザ退会実行' ,
			'Tv_Action_UserSearchDo' => 'ユーザ検索実行' ,
			'Tv_Action_UserSearch' => 'ユーザ検索' ,
			'Tv_Action_UserSoundBuyDo' => 'ユーザサウンド購入実行' ,
			'Tv_Action_UserSoundBuy' => 'ユームサウンド購入' ,
			'Tv_Action_UserSoundHome' => 'ユーザサウンドホーム' ,
			'Tv_Action_UserSoundList' => 'ユーザサウンド一覧' ,
			'Tv_Action_UserSoundRanking' => 'ユーザサウンドランキング' ,
			'Tv_Action_UserSound' => 'ユーザサウンドポータル' ,
			'Tv_Action_UserTop' => 'ユーザ会員トップ' ,
			'Tv_Action_UserUtil' => 'ユーザユーティリティ' ,
		);
		return $action_array;
	}


}

?>
